[versions]
kotlin = "1.7.0"
minecraft = "1.19"
quilt_mappings = "1.19+build.1"
quilt_loader = "0.17.0-beta.3"
quilt_stl = "2.0.0-beta.2+1.19"
energy = "2.0"

[libraries]
kotlin_stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin_reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlin" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
quilt_mappings = { module = "org.quiltmc:quilt-mappings", version.ref = "quilt_mappings" }
quilt_loader = { module = "org.quiltmc:quilt-loader", version.ref = "quilt_loader" }
quilt_stl = { module = "org.quiltmc:qsl", version.ref = "quilt_stl" }
energy = { module = "org.quantumclient:Energy", version.ref = "energy" }

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
loom = { id = "org.quiltmc.loom", version = "0.12.+" }